"""add crew_members table

Revision ID: 2779c7b7698b
Revises: 9a5de97a6a42
Create Date: 2026-08-21 14:07:55.784636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2779c7b7698b'
down_revision: Union[str, Sequence[str], None] = '9a5de97a6a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marks', 'regatta_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('marks', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('marks', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('fk_marks_regatta_id_regattas'), 'marks', type_='foreignkey')
    op.create_foreign_key(None, 'marks', 'regattas', ['regatta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_marks_regatta_id_regattas'), 'marks', 'regattas', ['regatta_id'], ['id'], ondelete='CASCADE')
    op.alter_column('marks', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('marks', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('marks', 'regatta_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
